version: '3'

services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    # image: nginx1
    ports:
      - 443:443

  mariadb:
    container_name: database
    build: requirements/mariadb
    # image: mariadb1
    environment:
      MARIADB_ROOT_PASSWORD : rootpassword
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
       - /requirements/mariadb/
    networks:
      - backnet

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    # image: wordpress1
    depends_on:
      - mariadb

networks:
  backnet:

volumes:
  mariadb:
  wordpress:
