version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - '443:443'
    restart: unless-stopped

  mariadb:
    container_name: database
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD : rootpassword
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
       - mariadb_data:/requirements/mariadb/
    networks:
      - backnet
    ports:
      - '3306:3306'
   # restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
  #  environment:
   #   WORDPRESS_DB_HOST: db:3306
   #   WORDPRESS_DB_USER: wordpress
   #   WORDPRESS_DB_PASSWORD: wordpress
   # working_dir: /var/www/html
    volumes:
       - wordpress:/requirements/wordpress/
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
   # restart: unless-stopped

networks:
  backnet:

volumes:
  mariadb_data:
  wordpress:
